import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wYiDAAAAEDUAgnCACPRglABIAAAABBAAXBfADEDAIAAAAABAcAKCOBDAABCBjFAEBAAJAACNAABESKAaCAABBFA4QIKAAAABCEJACABAJAiQAACCABAABAAWDl0AoPAfAeBg9CBBBADBEA');
