import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('ghALAPAwVIAiSCizAgqCj1Ag8AAACBkkBwbjBsVADBsEAjFBjLAEAk5BlhDitBBBcBi7BhABu7BICw3jAMAVBmsA3T7AkNBjiACAl9BhVBheAiXBiSCiPBj4A1JlACBioALAPAhAAwrzBwT8EgrDi8Bh0Dh-CiABFAPBhXBABhrAmgBl0BEOhoBj4CoEAAAj6BhWBmjBqzB0t0BiEAhABKAtSA04FAx3nA');
